In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a)

[1 2 3]


In [6]:
a[0] = 5

In [8]:
print(a)

[5 2 3]


In [9]:
b = np.array([[1,2,3],[4,5,6]])

In [10]:
print(b.shape)

(2, 3)


In [11]:
# Create a constant array

c = np.full((2,2), 7)  

In [12]:
print(c)

[[7 7]
 [7 7]]


In [13]:
# Create a 2x2 identity matrix
d = np.eye(2)         

In [15]:
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [16]:
# Create an array filled with random values
e = np.random.random((2,2))  

In [18]:
print(e)

[[ 0.65182085  0.46091326]
 [ 0.16052079  0.94644839]]


In [19]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a =   np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [21]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

In [23]:
print(b)

[[2 3]
 [6 7]]


In [24]:
b[0, 0] = 77

In [26]:
print(b)

[[77  3]
 [ 6  7]]


In [27]:
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
